# Generated by Django 4.0.8 on 2023-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/'),
        ),
    ]
