# Generated by Django 4.0.8 on 2023-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0013_alter_product_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos_pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='marketcourses/static/marketcourses/img')),
            ],
        ),
    ]
