# Generated by Django 4.0.8 on 2023-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0014_archivos_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketcourses/static/marketcourses/img'),
        ),
    ]
