# Generated by Django 4.0.8 on 2023-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0015_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marketcourses/static/marketcourses/img')),
            ],
        ),
    ]
