# Generated by Django 4.0.8 on 2023-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0016_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='opiniones',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='marketcourses/static/marketcourses/img'),
        ),
    ]
