# Generated by Django 4.0.8 on 2023-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0017_estudiantes_opiniones_alter_estudiantes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='estrellas',
            field=models.IntegerField(blank=True, choices=[(1, 'Muy bien'), (2, 'Buena'), (3, 'Mala')], default=None, null=True),
        ),
    ]
