# Generated by Django 4.0.8 on 2023-07-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0018_estudiantes_estrellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='opinion_completa',
            field=models.BooleanField(default=False),
        ),
    ]
