# Generated by Django 4.0.8 on 2023-07-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0019_estudiantes_opinion_completa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='opinion_completa',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
