# Generated by Django 4.0.8 on 2023-07-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0020_alter_estudiantes_opinion_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='tiene_img',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
