# Generated by Django 4.0.8 on 2023-07-16 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketcourses', '0021_estudiantes_tiene_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
