# Generated by Django 4.0.8 on 2023-07-16 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketcourses', '0027_alter_estudiantes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='tiene_img',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='user',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
