# Generated by Django 4.0.8 on 2023-07-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0028_alter_estudiantes_apellido_alter_estudiantes_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
