# Generated by Django 4.0.8 on 2023-07-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketcourses', '0029_estudiantes_password_estudiantes_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='password',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='username',
        ),
    ]
