# Generated by Django 4.0.8 on 2023-07-18 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketcourses', '0030_remove_estudiantes_password_remove_estudiantes_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
